import NLS.ZakharovShabat.SourcePhysicalEnergyActionDifferential
import NLS.ZakharovShabat.SourceFiniteGapHamiltonianODE

/-! # Finite-gap trajectories follow the actual physical energy Hamiltonian

At each time the source derivative is the original Poisson Hamiltonian
direction of a bounded Hilbert cotangent whose H¹ restriction is the full
physical NLS energy derivative. Identifying this cotangent with the
classical spatial differential expression is a separate step.
-/
noncomputable section
open Set NLS.Poisson
namespace NLS.ZakharovShabat.SourceAbelianMomentAtlas
variable {W P V B X : Set (CoeffPair 2)}
variable {s t : (n : ℤ) → CoeffPair 2 → DeletedCoeff 2 n}

/-- At every time a finite-gap spectral trajectory is generated by the
actual physical energy differential and the original source Poisson structure. -/
theorem exists_physicalEnergyHamiltonian_ODE
    (A : SourceAbelianMomentAtlas (by simp) (by norm_num) W s)
    (hs : SourcePsiIsolatingComplexExtension (by simp) (by norm_num) P s)
    (D : SourceBirkhoffMapComplexData (by simp) (by norm_num) V B X t)
    (φ : realTypeSourceSubmodule 2) (hf : φ ∈ sourceFiniteGapLocus (by simp) (by norm_num))
    (time : ℝ) :
    let ψ := A.hamiltonianOrdinarySourceFlow D le_rfl φ time
    let hfψ := A.hamiltonianOrdinarySourceFlow_finiteGap D le_rfl φ hf time
    ∃ L : CoeffPair 2 →L[ℂ] ℂ,
      HasFDerivAt periodOneSobolevHamiltonian (L.comp sobolevSourceInclusion)
        (sourceFiniteGapSobolevPair (by simp) (by norm_num) ψ hfψ) ∧
      HasDerivAt (fun r => (A.hamiltonianOrdinarySourceFlow D le_rfl φ r).val)
        (sourceHamiltonianDirection le_rfl L) time := by
  classical
  dsimp only
  let S := hf.toFinset
  have hclosed (n : ℤ) (hn : n ∉ S) :
      sourcePeriodicGapDisplacement (by simp) (by norm_num) φ.val n = 0 := by
    rw [sourcePeriodicGapDisplacement_apply]
    by_contra h
    exact hn (hf.mem_toFinset.mpr h)
  have hz (n : ℤ) (hn : n ∉ S) :
      (sourceComplexBirkhoffMap (by simp) (by norm_num) t φ.val).1 n = 0 ∧
      (sourceComplexBirkhoffMap (by simp) (by norm_num) t φ.val).2 n = 0 := by
    obtain ⟨hx,hy⟩ := D.real_closed_gap_zero φ.val (D.real_subset φ.property) φ.property n (hclosed n hn)
    simp only [sourceComplexBirkhoffMap,Birkhoff.rectangularToComplex_fst,
      Birkhoff.rectangularToComplex_snd,hx,hy,mul_zero,sub_zero,add_zero,and_self]
  let ψ := A.hamiltonianOrdinarySourceFlow D le_rfl φ time
  have hfψ := A.hamiltonianOrdinarySourceFlow_finiteGap D le_rfl φ hf time
  have hclosedψ (n : ℤ) (hn : n ∉ S) :
      sourcePeriodicGapDisplacement (by simp) (by norm_num) ψ.val n = 0 := by
    have hzφ := (sourceComplexAction_nonneg_and_eq_zero_iff_gap_zero (by simp) (by norm_num)
      n φ.val φ.property).2.2.mpr (hclosed n hn)
    apply (sourceComplexAction_nonneg_and_eq_zero_iff_gap_zero (by simp) (by norm_num)
      n ψ.val ψ.property).2.2.mp
    exact (A.hamiltonianOrdinarySourceFlow_action D le_rfl φ time n).trans hzφ
  let a := sourceFiniteGapSobolevPair (by simp) (by norm_num) ψ hfψ
  have ha : sobolevSourceInclusion a = ψ.val := sobolevSourceInclusion_sourceFiniteGapSobolevPair ψ hfψ
  have hr : IsRealType (CoeffPair.toMax 2 (sobolevSourceInclusion a)) := ha ▸ ψ.property
  let L : CoeffPair 2 →L[ℂ] ℂ :=
    ∑ n ∈ S, (A.ordinaryPhaseFrequency le_rfl ψ n : ℂ) •
      fderiv ℂ (sourceComplexAction (by simp) (by norm_num) n) ψ.val
  have he : fderiv ℂ periodOneSobolevHamiltonian a = L.comp sobolevSourceInclusion := by
    apply ContinuousLinearMap.ext
    intro h
    have hd := A.periodOneSobolevHamiltonian_fderiv_eq_finite_sum hs ⟨a,hr⟩ S
      (by simpa only [ha] using hclosedψ) h
    have hψ : (⟨sobolevSourceInclusion a,hr⟩ : realTypeSourceSubmodule 2) = ψ := Subtype.ext ha
    simpa only [hψ,ha,L,ContinuousLinearMap.comp_apply,sum_apply,smul_apply,smul_eq_mul] using hd
  refine ⟨L,?_,?_⟩
  · exact he ▸ (analyticAt_periodOneSobolevHamiltonian a).differentiableAt.hasFDerivAt
  · have hd := A.hasDerivAt_hamiltonianOrdinarySourceFlow_autonomous hs D le_rfl le_rfl φ S hz time
    simpa only [L,map_sum,map_smul,sourceFiniteActionHamiltonianVector,sourceHamiltonianVector] using! hd

end NLS.ZakharovShabat.SourceAbelianMomentAtlas
