import NLS.Fourier.HilbertDoubling

/-!
# Hilbert transforms at every dyadic exponent

Starting at Parseval's exponent `2`, Cotlar doubling constructs actual continuous
ordinary and shifted Hilbert transforms at `2^(n+1)`. The bounds are explicit,
and these exponents are unbounded. Interpolation and duality are still needed
for the full range `1 < p < ∞`.
-/

noncomputable section
open Complex
open scoped ENNReal
namespace NLS.Fourier

/-- The exponents reached by repeated Cotlar doubling, starting with `2`. -/
def dyadicHilbertExponent : ℕ → ℝ≥0∞
  | 0 => 2
  | n+1 => 2 * dyadicHilbertExponent n

theorem dyadicHilbertExponent_eq (n : ℕ) : dyadicHilbertExponent n = 2 ^ (n+1) := by
  induction n with
  | zero => simp [dyadicHilbertExponent]
  | succ n ih => rw [dyadicHilbertExponent, ih, pow_succ]; exact mul_comm _ _

theorem one_lt_dyadicHilbertExponent (n : ℕ) : 1 < dyadicHilbertExponent n := by
  rw [dyadicHilbertExponent_eq]
  exact one_lt_pow' (by norm_num) (Nat.succ_ne_zero n)

instance (n : ℕ) : Fact (1 ≤ dyadicHilbertExponent n) :=
  ⟨(one_lt_dyadicHilbertExponent n).le⟩

theorem dyadicHilbertExponent_ne_top (n : ℕ) : dyadicHilbertExponent n ≠ ⊤ := by
  rw [dyadicHilbertExponent_eq]
  exact ENNReal.pow_ne_top (by norm_num)

@[simp] theorem dyadicHilbertExponent_toReal (n : ℕ) :
    (dyadicHilbertExponent n).toReal = (2 : ℝ) ^ (n + 1) := by
  simp [dyadicHilbertExponent_eq]

theorem dyadicHilbertExponent_succ_toReal (n : ℕ) :
    (dyadicHilbertExponent (n+1)).toReal = 2 * (dyadicHilbertExponent n).toReal := by
  simp only [dyadicHilbertExponent_toReal, pow_succ]
  ring

theorem dyadicHilbertExponent_holder (n : ℕ) :
    (dyadicHilbertExponent (n+1)).HolderTriple (dyadicHilbertExponent (n+1))
      (dyadicHilbertExponent n) := by
  rw [ENNReal.holderTriple_iff]
  simp only [dyadicHilbertExponent_eq]
  apply (ENNReal.toReal_eq_toReal_iff' (by finiteness) (by finiteness)).mp
  rw [ENNReal.toReal_add (by finiteness) (by finiteness)]
  simp only [ENNReal.toReal_inv, ENNReal.toReal_pow, ENNReal.toReal_ofNat]
  rw [pow_succ]
  field_simp
  ring

/-- Iterating the proved estimate, with no assumption of Hilbert boundedness. -/
def dyadicHilbertEstimate : (n : ℕ) → HilbertEstimate (dyadicHilbertExponent n)
  | 0 => {
      one_lt := one_lt_dyadicHilbertExponent 0
      ne_top := dyadicHilbertExponent_ne_top 0
      bound := discreteHilbertBound
      bound_nonneg := discreteHilbertBound_pos.le
      finite_bound := norm_finiteHilbert_two_le }
  | n+1 => by
    letI := dyadicHilbertExponent_holder n
    exact (dyadicHilbertEstimate n).doubleTo (one_lt_dyadicHilbertExponent (n+1))
      (dyadicHilbertExponent_ne_top (n+1)) (dyadicHilbertExponent_succ_toReal n)

/-- The uniform constant produced by the dyadic induction. -/
def dyadicHilbertBound (n : ℕ) : ℝ := (dyadicHilbertEstimate n).bound

@[simp] theorem dyadicHilbertBound_zero : dyadicHilbertBound 0 = discreteHilbertBound := rfl

theorem dyadicHilbertBound_succ (n : ℕ) :
    dyadicHilbertBound (n+1) = 2 * dyadicHilbertBound n + 3 * ‖hilbertSquareCoeffs‖ + 1 := rfl

/-- A closed form for the (non-optimal) bound generated by doubling. -/
theorem dyadicHilbertBound_eq (n : ℕ) :
    dyadicHilbertBound n = 2^n * discreteHilbertBound +
      (2^n - 1) * (3 * ‖hilbertSquareCoeffs‖ + 1) := by
  induction n with
  | zero => simp
  | succ n ih => rw [dyadicHilbertBound_succ, ih, pow_succ]; ring

/-- The ordinary discrete Hilbert transform at exponent `2^(n+1)`. -/
def dyadicHilbert (n : ℕ) :
    Coeff (dyadicHilbertExponent n) →L[ℂ] Coeff (dyadicHilbertExponent n) :=
  (dyadicHilbertEstimate n).operator

theorem dyadicHilbert_finite (n : ℕ) (a : ℤ →₀ ℂ) (k : ℤ) :
    dyadicHilbert n (Coeff.ofFinsupp a) k = finiteHilbert a k :=
  (dyadicHilbertEstimate n).operator_finite a k

theorem norm_dyadicHilbert_apply_le (n : ℕ) (a : Coeff (dyadicHilbertExponent n)) :
    ‖dyadicHilbert n a‖ ≤ dyadicHilbertBound n * ‖a‖ :=
  (dyadicHilbertEstimate n).norm_operator_apply_le a

/-- The shifted discrete Hilbert transform at exponent `2^(n+1)`. -/
def dyadicShiftedHilbert (n : ℕ) :
    Coeff (dyadicHilbertExponent n) →L[ℂ] Coeff (dyadicHilbertExponent n) :=
  (dyadicHilbertEstimate n).shifted

theorem dyadicShiftedHilbert_finite (n : ℕ) (a : ℤ →₀ ℂ) (k : ℤ) :
    dyadicShiftedHilbert n (Coeff.ofFinsupp a) k =
      a.sum (fun j z => z * (2 / ((Real.pi : ℂ) * (2*j - 2*k - 1)))) :=
  (dyadicHilbertEstimate n).shifted_finite a k

theorem norm_dyadicShiftedHilbert_apply_le (n : ℕ) (a : Coeff (dyadicHilbertExponent n)) :
    ‖dyadicShiftedHilbert n a‖ ≤
      Real.pi⁻¹ * (dyadicHilbertBound n + ‖hilbertCorrectionCoeffs‖) * ‖a‖ :=
  (dyadicHilbertEstimate n).norm_shifted_apply_le a

/-- The proved exponents eventually exceed any prescribed real exponent. -/
theorem dyadicHilbertExponent_unbounded (r : ℝ) :
    ∃ n : ℕ, r < (dyadicHilbertExponent n).toReal := by
  have ht := tendsto_pow_atTop_atTop_of_one_lt (by norm_num : (1 : ℝ) < 2)
  obtain ⟨n, hn⟩ := (ht.eventually_gt_atTop r).exists
  refine ⟨n, hn.trans_le ?_⟩
  rw [dyadicHilbertExponent_toReal, pow_succ]
  nlinarith [show (0 : ℝ) ≤ 2^n by positivity]

end NLS.Fourier
